#
# Get ghdl and run all the test benches
#
language: C

sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
    - libftdi1-dev
    - qt5-default

script:
  - .travis/build.sh

