#
# Get ghdl and run all the test benches
#
language: C

sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - qt5-default
    - qttools5-dev-tools
    - libftdi1-dev

script:
  - .travis/build.sh

